
sass:
  sass_dir: css/_scss
  style: :compressed

# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            DATA CORRUPT
tagline:          ''
description:      ''
url:              http://lydia.cool

author:
  name:           'Lydia Krupp Hunter'
  url:            https://twitter.com/funionnn

paginate:         3

gems:
  - jemoji
# Custom vars
